packetbeat.interfaces.device: any

packetbeat.flows:
  timeout: 30s
  period: 5s

packetbeat.protocols.dns:
  ports: [53]
  include_authorities: true
  include_additionals: true

packetbeat.protocols.http:
  ports: [80, 5601, 9200, 8080, 8081, 5000, 8002]

packetbeat.protocols.memcache:
  ports: [11211]

packetbeat.protocols.mysql:
  ports: [3306]

packetbeat.protocols.pgsql:
  ports: [5432]

packetbeat.protocols.redis:
  ports: [6379]

packetbeat.protocols.thrift:
  ports: [9090]

packetbeat.protocols.mongodb:
  ports: [27017]

packetbeat.protocols.cassandra:
  ports: [9042]

processors:
- add_cloud_metadata: ~

output.elasticsearch:
  enabled: true
  hosts: '${ELASTICSEARCH_HOSTS}'
  username: '${ELASTICSEARCH_USERNAME}'
  password: '${ELASTICSEARCH_PASSWORD}'
  protocol: https
  pipeline: geoip-info
  ssl.certificate_authorities:
    - ${PACKETBEAT_CERTS_DIR}/ca/ca.crt
  ssl.certificate: ${PACKETBEAT_CERTS_DIR}/packetbeat.crt
  ssl.key: ${PACKETBEAT_CERTS_DIR}/packetbeat.key
  index: 'honeys-packet'
setup.template.name: "honeyspacket"
setup.template.pattern: "honeyspacket-*"
